# Azure pipeline reference: https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    steps:
    - pwsh: ./bootstrap.ps1
    - pwsh: ./build.ps1
- stage: test
  displayName: Test
  jobs:
  - job: test
    steps:
    - pwsh: cd build && ctest