# Azure pipeline reference: https://aka.ms/yaml

trigger:
- master
- container_build

pr:
- master

parameters:
- name: buildType
  displayName: Native or containerized build
  type: string
  default: native
  values:
  - native
  - container

jobs:
- ${{ if contains(parameters.buildType, 'native') }}:
  - job:
    strategy:
      matrix:
        windows:
          imageName: 'windows-latest'
        linux:
          imageName: 'ubuntu-latest'
    pool:
      vmImage: $(imageName)
    displayName: Build (Native)
    steps:
    - task: Cache@2
      inputs:
        key: 'vcpkg | "$(Agent.OS)"'
        path: $(Build.Repository.LocalPath)/vcpkg
        cacheHitVar: DOCKER_CACHE_RESTORED
      displayName: Caching vcpkg
    - pwsh: ./Bootstrap.ps1
      displayName: Boostrap
      condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
    - pwsh: ./Build.ps1
      displayName: Build
    - pwsh: cd build && ctest
      displayName: Test

- ${{ if contains(parameters.buildType, 'container') }}:
  - job:
    strategy:
      matrix:
        windows:
          imageName: 'windows-latest'
        linux:
          imageName: 'ubuntu-latest'
    pool:
      vmImage: $(imageName)
    displayName: Build (Container)
    steps:
    - pwsh: ./BuildImage.ps1
      displayName: Build Docker image
    - pwsh: ./BuildContainerized.ps1
      displayName: Build
    - pwsh: cd build && ctest
      displayName: Test