# Azure pipeline reference: https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build
  steps:
  - script: echo Build
- stage: test
  displayName: test
  steps:
  - script echo Test