# Azure pipeline reference: https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  displayName: Build
  steps:
  - pwsh: ./bootstrap.ps1
  - pwsh: ./build.ps1
- job: test
  displayName: Test
  steps:
  - pwsh: cd build && ctest