FROM marcusmaximus/msvc-buildtools:2019-servercore-ltsc2019

RUN powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN choco install -y pwsh && \
    choco install -y git --params "/GitOnlyOnPath /NoGitLfs /NoShellIntegration" && \
    choco install -y cmake --installargs "ADD_CMAKE_TO_PATH=System"

SHELL ["pwsh", "-NoLogo", "-Command"]

#USER ContainerUser
WORKDIR C:\\cpp-project

COPY .\\Bootstrap.ps1 .
RUN pwsh -File .\\Bootstrap.ps1

ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "pwsh", "-NoLogo", "-Command"]
CMD ["pwsh"]