ARG FROM_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
FROM ${FROM_IMAGE}

SHELL ["cmd", "/S", "/C"]

ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\\TEMP\\vs_buildtools.exe
RUN C:\\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache \
    --installPath C:\\BuildTools \
    --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0

RUN powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN choco install -y pwsh && \
    choco install -y git --params "/GitOnlyOnPath /NoGitLfs /NoShellIntegration" && \
    choco install -y cmake --installargs "ADD_CMAKE_TO_PATH=System"

#USER ContainerUser
WORKDIR C:\\cpp-project

COPY .\\Bootstrap.ps1 .
RUN pwsh -File .\\Bootstrap.ps1

ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "pwsh", "-NoLogo", "-Command"]
CMD ["pwsh"]