FROM mcr.microsoft.com/powershell:ubuntu-20.04

RUN apt-get update && \
    apt-get install -y git g++ cmake curl unzip tar

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd --gid ${GROUP_ID} build && \
    useradd --create-home --gid ${GROUP_ID} --uid ${USER_ID} build
USER build

WORKDIR /home/build

COPY --chown=build ./Bootstrap.ps1 .
RUN pwsh -File ./Bootstrap.ps1

ENTRYPOINT ["pwsh", "-NoLogo", "-Command"]
CMD ["pwsh"]